from django.db import models
from django.db.models.fields import CharField

# Create your models here.

class Details(models.Model):
    Scheme_name =CharField(max_length=100, blank=True, null=True)
    tire_name =CharField(max_length=100, blank=True, null=True)
    employers_name = models.CharField(max_length=100, blank=True, null=True)
    enrolment_no = models.CharField(max_length=100, blank=True, null=True)
    employer_address = models.CharField(max_length=100, blank=True, null=True)
    branch = models.CharField(max_length=100, blank=True, null=True)
    entry_date = models.DateField(blank=True, null=True)
    employee_gender = models.CharField(max_length=100, blank=True, null=True)

    member_title = models.CharField(max_length=100, blank=True, null=True)
    surname = models.CharField(max_length=100, blank=True, null=True)
    firstname = models.CharField(max_length=100, blank=True, null=True)
    othername = models.CharField(max_length=100, blank=True, null=True)
    identification_number = models.CharField(max_length=100, blank=True, null=True)
    identification_type = models.CharField(max_length=100, blank=True, null=True)
    marital_status = models.CharField(max_length=100, blank=True, null=True)
    gender = models.CharField(max_length=100, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    placeofbirth = models.CharField(max_length=100, blank=True, null=True)
    region = models.CharField(max_length=100, blank=True, null=True)
    district = models.CharField(max_length=100, blank=True, null=True)
    town = models.CharField(max_length=100, blank=True, null=True)
    residential_address = models.CharField(max_length=100, blank=True, null=True)
    postal_address = models.CharField(max_length=100, blank=True, null=True)
    telephone_number = models.CharField(max_length=100, blank=True, null=True)
    work_number = models.CharField(max_length=100, blank=True, null=True)
    employer_address1 = models.CharField(max_length=100, blank=True, null=True)
    employer_gender = models.CharField(max_length=100, blank=True, null=True)
    fathers_name = models.CharField(max_length=100, blank=True, null=True)
    fathers_address = models.CharField(max_length=100, blank=True, null=True)
    mothers_name = models.CharField(max_length=100, blank=True, null=True)
    mothers_address = models.CharField(max_length=100, blank=True, null=True)
    ssnit_number = models.CharField(max_length=100, blank=True, null=True)
    date_of_entry = models.DateField(blank=True, null=True) 

    trustee_title = models.CharField(max_length=100, blank=True, null=True)
    member_name = models.CharField(max_length=100, blank=True, null=True)
    employee_number = models.CharField(max_length=100, blank=True, null=True)
    employer_branch = models.CharField(max_length=100, blank=True, null=True)
    employer_name = models.CharField(max_length=100, blank=True, null=True)

    dependant_surname = models.CharField(max_length=100, blank=True, null=True)
    dependant_firstname = models.CharField(max_length=100, blank=True, null=True)
    dependant_gender = models.CharField(max_length=100, blank=True, null=True)
    dependant_dob = models.CharField(max_length=100, blank=True, null=True)
    percentage_benefit = models.CharField(max_length=100, blank=True, null=True)
    relationship = models.CharField(max_length=100, blank=True, null=True)

    dependant_surname1 = models.CharField(max_length=100, blank=True, null=True)
    dependant_firstname1 = models.CharField(max_length=100, blank=True, null=True)
    dependant_gender1 = models.CharField(max_length=100, blank=True, null=True)
    dependant_dob1 = models.CharField(max_length=100, blank=True, null=True)
    percentage_benefit1 = models.CharField(max_length=100, blank=True, null=True)
    relationship1 = models.CharField(max_length=100, blank=True, null=True)

    dependant_surname2 = models.CharField(max_length=100, blank=True, null=True)
    dependant_firstname2 = models.CharField(max_length=100, blank=True, null=True)
    dependant_gender2 = models.CharField(max_length=100, blank=True, null=True)
    dependant_dob2 = models.CharField(max_length=100, blank=True, null=True)
    percentage_benefit2 = models.CharField(max_length=100, blank=True, null=True)
    relationship2 = models.CharField(max_length=100, blank=True, null=True)

    dependant_surname3 = models.CharField(max_length=100, blank=True, null=True)
    dependant_firstname3 = models.CharField(max_length=100, blank=True, null=True)
    dependant_gender3 = models.CharField(max_length=100, blank=True, null=True)
    dependant_dob3 = models.CharField(max_length=100, blank=True, null=True)
    percentage_benefit3 = models.CharField(max_length=100, blank=True, null=True)
    relationship3 = models.CharField(max_length=100, blank=True, null=True)

    dependant_surname4 = models.CharField(max_length=100, blank=True, null=True)
    dependant_firstname4 = models.CharField(max_length=100, blank=True, null=True)
    dependant_gender4 = models.CharField(max_length=100, blank=True, null=True)
    dependant_dob4 = models.CharField(max_length=100, blank=True, null=True)
    percentage_benefit4 = models.CharField(max_length=100, blank=True, null=True)
    relationship4 = models.CharField(max_length=100, blank=True, null=True)