# Generated by Django 4.0 on 2021-12-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Scheme_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tire_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('enrolment_no', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_address', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('employee_gender', models.CharField(blank=True, max_length=100, null=True)),
                ('member_title', models.CharField(blank=True, max_length=100, null=True)),
                ('surname', models.CharField(blank=True, max_length=100, null=True)),
                ('firsname', models.CharField(blank=True, max_length=100, null=True)),
                ('othername', models.CharField(blank=True, max_length=100, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=100, null=True)),
                ('identification_type', models.CharField(blank=True, max_length=100, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('placeofbirth', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('town', models.CharField(blank=True, max_length=100, null=True)),
                ('residential_address', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_address', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('work_number', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_address1', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_gender', models.CharField(blank=True, max_length=100, null=True)),
                ('fathers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('fathers_address', models.CharField(blank=True, max_length=100, null=True)),
                ('mothers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mothers_address', models.CharField(blank=True, max_length=100, null=True)),
                ('ssnit_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_entry', models.DateField(blank=True, null=True)),
                ('trustee_title', models.CharField(blank=True, max_length=100, null=True)),
                ('member_name', models.CharField(blank=True, max_length=100, null=True)),
                ('employee_number', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('employer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('depndant_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('dependant_firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('dependant_gender', models.CharField(blank=True, max_length=100, null=True)),
                ('dependant_dob', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage_benefit', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
